# Generated by Django 4.1.4 on 2023-01-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cocktails", "0002_remove_cocktail_author_alter_cocktail_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cocktail",
            name="author",
            field=models.ForeignKey(
                # default=django.utils.timezone.now,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
