# Generated by Django 4.1.4 on 2023-01-05 08:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cocktails", "0003_cocktail_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="UOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uom", models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="alcohol_content",
        ),
        migrations.AlterField(
            model_name="cocktail",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="ingredients",
        ),
        migrations.AlterField(
            model_name="cocktail",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "alcohol_content",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("uom", models.ManyToManyField(to="cocktails.uom")),
            ],
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(to="cocktails.ingredient"),
        ),
    ]
