# Generated by Django 4.1.4 on 2023-01-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0004_uom_remove_cocktail_alcohol_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="uom",
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cocktails.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cocktails.uom",
            ),
        ),
    ]
