# Generated by Django 4.1.4 on 2023-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0006_ingredient_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=3, null=True
            ),
        ),
    ]
