# Generated by Django 4.1.4 on 2023-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0007_alter_ingredient_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="uom",
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ManyToManyField(to="cocktails.ingredient"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="uom",
            field=models.ManyToManyField(to="cocktails.uom"),
        ),
    ]
