# Generated by Django 4.1.4 on 2023-01-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cocktails",
            "0008_remove_cocktail_ingredients_remove_ingredient_uom_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="cocktail",
            name="ingredients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cocktails.ingredient",
            ),
        ),
    ]
