# Generated by Django 4.1.4 on 2023-01-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0009_remove_cocktail_ingredients_cocktail_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="uom",
        ),
        migrations.AddField(
            model_name="cocktail",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cocktails.uom",
            ),
        ),
        migrations.AddField(
            model_name="cocktail",
            name="quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cocktails.quantity",
            ),
        ),
    ]
