# Generated by Django 4.1.4 on 2023-02-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails", "0010_quantity_remove_ingredient_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cocktail",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="cocktail",
            name="uom",
        ),
        migrations.AddField(
            model_name="cocktail",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="cocktail",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="cocktails.cocktail",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Quantity",
        ),
        migrations.DeleteModel(
            name="UOM",
        ),
    ]
